name: My First Workflow

on: push

jobs:
    fist_job:
        runs-on: ubuntu-latest
        steps:
            - name: Wecome message
              run: echo "My fisrt Github Action Job"

            - name: List files
              run: ls

            - name: Read file
              run: cat README.md
